# Default values for node-health.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ahabd:
  docker:
    apiVersion: 1.24
  image: 
    name: docker.io/jpangms/ahabd
    tag: latest
  period: 5m

kured:
  image: 
    name: quay.io/weaveworks/kured
    tag: support-k8s-1.10-5731b98
  period: 5m

image:
  pullPolicy: Always
